services:
  cdn_selector:
    container_name: cdn_selector
    build: .
    ports:
      - "8080:8080"
    networks:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: cdnselector
      POSTGRES_PASSWORD: cdnselector
      PGDATA: /data/postgres
    # volumes:
    #    - ./data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: cdnselector@cdnselector.com.vn
  #     PGADMIN_DEFAULT_PASSWORD: cdnselector
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   # volumes:
  #   #    - ./pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "81:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge
# volumes:
#     postgres:
#     pgadmin: